-- Löschen der Tabellen
DROP TABLE IF EXISTS UEB03A.TBDPOSTFILESTREET;
DROP TABLE IF EXISTS UEB03A.TBDPOSTFILEZIP;

-- Löschen der Tablespaces
DROP TABLESPACE STBDPOSTFILESTREET;
DROP TABLESPACE STBDPOSTFILEZIP;
